FROM nvidia/cuda:12.1.1-runtime-ubuntu22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 python3-pip \
    libx11-6 libxext6 libxrender1 libxkbcommon-x11-0 \
    libglib2.0-0 libglu1-mesa mesa-utils xauth \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir PySide6 pyqtgraph nibabel numpy

WORKDIR /app
COPY simple_nii_viewer.py /app/simple_nii_viewer.py

CMD ["/bin/bash"]
